import { useState, useEffect } from 'react'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'

import MainCard from '../components/main_card'
import styles from '../styles/Home.module.css'

export default function Home() {
  
  // Move to lib, future
  const [size, setSize] = useState(0);

  useEffect(()=>{
    if (typeof window !== 'undefined') {
      setSize(window.innerWidth);
    };
  },[])
  //
  

  return (
    <div className={styles.container}>
      <Head>
        <title>MOORIM-TC - The Best Engineering Partner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{height:'3rem', position:'sticky', top:'0px', display:'flex', flexDirection:'row', alignItems:'center', backgroundColor:'white', zIndex:'10'}}>
        
        <Link href={'category/solutions'}>
          <a>
            Solutions
          </a>
        </Link>
        
        <Link href={`/category/portfolio?size=${size}`}>
          <a style={{marginLeft:'2rem'}}>
          Portfolio
          </a>
        </Link>
      </div>

      <main className={styles.main}>
        <div className={styles.companyHead}>
          <Image 
            className={styles.bg}
            src="/d301.jpeg"
            alt="bg"
            layout="fill"
            objectFit='cover'
            objectPosition='center'
          />
          <div className={styles.title} style={{fontSize : size > 800 ? '5rem' : '2.4rem'}}>
            MOORIM T.C.
          </div>
          <div className={styles.subTitle} style={{fontSize : size > 800 ? '1.6rem' : '1.0rem'}}>
            &ldquo;Your Best Engineering Partner&rdquo;
          </div>
        </div>
        
        <div className={styles.contentsContainer}>
          <div className={styles.textContainer}>
            <div style={{paddingLeft:8, fontSize:24, marginBottom:8, color:'#1272CB', textAlign:'start'}}>
              &ldquo;다재다능한,
            </div>
            <div style={{paddingRight:8, fontSize:24, marginBottom:16, color:'#1272CB', textAlign:'end'}}>
              당신의 엔지니어링 파트너&rdquo;
            </div>
            <div style={{paddingLeft:10, fontSize:14, marginBottom:16, lineHeight:1.5, color:'#3E3D3D'}}>
              NVH(Noise Vibration Harshness)전공<br/>
              + 차량 NVH Engineering<br/>
              ++ 차량 R&H Engineering<br/>
              +++ Machine Learning & Coding Skill
            </div>
            <div style={{paddingLeft:10, fontSize:14, marginBottom:16, lineHeight:1.5}}>
              무림티씨를 선택해야하는 이유
            </div>
            <div style={{paddingLeft:10, fontSize:14, marginBottom:16, lineHeight:1.5, color:'#3E3D3D'}}>
              1. 폭넓은 경험에서 제공되는 수준높은 엔지니어링 서비스<br/>
              2. 전통적인 계측, 분석기법부터 최신 AI알고리즘까지.<br/>
              3. 끊임없는 연구개발을 통한 차별화된 서비스<br/>
            </div>
          </div>

          <div className={styles.grid}>    

            <MainCard size={size} link={`/category/test_solution?size=${size}`}>            
              <h2>Test Solution</h2>
              <p>
                신호계측 / 학습용 데이터셋 / 특수 계측시스템
              </p>           
            </MainCard>

            <MainCard size={size} link={`/category/eng_solution?size=${size}`}>            
              <h2>Engineering Solution</h2>
              <p>
                데이터분석 / 문제해결 / 성능개선
              </p>            
            </MainCard>

            <MainCard size={size} link={`/category/ai_solution?size=${size}`}>
              <h2>AI Solution</h2>
              <p>
                머신러닝 / 데이터 Eng. / Feature Eng.
              </p>
            </MainCard>

            <MainCard size={size} link={`/category/sw_solution?size=${size}`}>            
              <h2>S/W Solution</h2>
              <p>
                PC App. / Web App. / Mobile App.
              </p>              
            </MainCard>

            <MainCard size={size} link={`/category/training_program?size=${size}`}>            
              <h2>Training Program</h2>
              <p>
                Python / Javascript / FrameWorks
              </p>              
            </MainCard>

            <MainCard size={size} link={`/category/portfolio?size=${size}`}> 
              <h2>Portfolio</h2>
              <p>
                Testing / Engineering / S/W
              </p>  
            </MainCard>

          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <div className={styles.footerDesc}>
          무림티씨 / shkim@moorim-tc.com
        </div>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={54} height={12} />
            {'    '}
            <Image src="/google-2015-google-new-google-icon.svg" alt="google Logo" width={36} height={12} />
          </span>
        </a>
      </footer>
    </div>
  )
}
